// This file was generated by `node scripts/swizzle.mjs`.
// It wraps the original component — edit freely.
// @moodle/lms/theme-original/block_workshoptodo/todolist resolves to the core (upstream) version of this
// component, bypassing any active theme overrides.
//
// To revert to the original, delete this file and rebuild.

import type {Props} from '@moodle/lms/theme-original/block_workshoptodo/todolist';
import OriginalComponent from '@moodle/lms/theme-original/block_workshoptodo/todolist';

/**
 * Classic theme wrapper for todolist.
 *
 * Renders the original component unchanged. Add your customisations here:
 *   - Extra markup before or after the original
 *   - Additional props or context
 *   - Side-effects (analytics, logging, etc.)
 *
 * @module     theme_classic/block_workshoptodo/todolist
 */
export default function Todolist(props: Props) {
    const completed = props.todos.filter(todo => todo.completed).length;
    const total = props.todos.length;
    const progress = total === 0 ? 0 : (completed / total) * 100;

    return (
        <section className="border-start border-4 border-primary ps-3">
            <div className="d-flex justify-content-between align-items-center mb-2">
                <strong>Today’s progress</strong>
                <span className="badge text-bg-primary">{completed} / {total}</span>
            </div>

            <div
                className="progress mb-3"
                role="progressbar"
                aria-label="Completed tasks"
                aria-valuenow={completed}
                aria-valuemin={0}
                aria-valuemax={total}
            >
                <div className="progress-bar" style={{width: `${progress}%`}} />
            </div>

            {total > 0 && completed === total && (
                <p className="text-success fw-semibold">All tasks complete.</p>
            )}
            <OriginalComponent {...props} />
        </section>
    );
}
